@extends('components.layouts.customer')

@section('preloads')
    <title>Welcome to Laravel</title>
    <meta name="page creator" content="Nghia Duong">
    <meta name="book name" content="{{ $book->name }}">
    <meta name="description" content="{{ $book->description }}">
    <meta name="author" content="{{ $book->author }}">
    <link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/customer/book/detail/style.css') }}">
    @livewireStyles
@endsection

@section('page')
    <div class='w-100 h-100 position-relative'>
        <div class="toast-container position-absolute top-0 end-0 p-3 h-100 overflow-y-auto hideBrowserScrollbar"
            id='toasts_container'>
        </div>
        <div class="container bg-light rounded p-3 mt-3">
            <div class="row justify-content-center align-items-center">
                <div class="col-12 col-md-5 d-flex flex-column justify-content-center align-items-center px-3">
                    <img src="{{ $book->image }}" class="rounded img-size"
                        alt="{{ $book->name }} {{ $book->edition }} image">
                </div>
                <div class="col-12 col-md-7 mt-md-0 mt-3">
                    <h1>{{ $book->name }}</h1>
                    <p class="fw-medium">{{ $book->edition }}</p>
                    <p>ISBN: {{ $book->isbn }}</p>
                    <p>Author: {{ $book->authors }}</p>
                    <p>Category: {{ $book->categories }}</p>
                    <p>Publisher: {{ $book->publisher }} </p>
                    <p>Publication date: {{ $book->publication_date }}</p>
                    @livewire('customer.book.detail.average-rating')

                    {{-- <form class='mt-3' id='addToCartForm'>
                        <div>
                            <?php if (!$physicalUnavailable) { ?>
                            <input type="radio" id="hardcover" name="bookType" class="btn-check" autocomplete="off">
                            <label class="btn border border-1 border-dark" for="hardcover">Hardcover</label>
                            <?php } ?>

                            <?php if (!$fileUnavailable) { ?>
                            <input type="radio" class="btn-check" name="bookType" id="ebook" autocomplete="off">
                            <label class="btn border border-1 border-dark <?php if (!$physicalUnavailable) {
                                echo 'ms-3';
                            } ?>"
                                for="ebook">E-book</label>
                            <?php } ?>
                        </div>

                        <?php if (!$fileUnavailable) { ?>
                        <h5 class='mt-3 none align-items-center mb-0' id='ebookPrice'>
                            <span class='fw-normal'>Price:</span>&nbsp;&nbsp;<span
                                class='<?php if ($bDiscount) {
                                    echo 'text-decoration-line-through';
                                } ?>'>$<?php echo $bFilePrice; ?></span><?php if ($bDiscount) {
                                    $discountedFilePrice = round(($bFilePrice * (100.0 - $bDiscount)) / 100, 2);
                                    echo "&nbsp;&nbsp;<span>\${$discountedFilePrice}</span>&nbsp;&nbsp;<svg width=\"32px\" height=\"32px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" stroke=\"#ff0000\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <g id=\"SVGRepo_bgCarrier\" stroke-width=\"0\"></g>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <g id=\"SVGRepo_tracerCarrier\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></g>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <g id=\"SVGRepo_iconCarrier\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M3.9889 14.6604L2.46891 13.1404C1.84891 12.5204 1.84891 11.5004 2.46891 10.8804L3.9889 9.36039C4.2489 9.10039 4.4589 8.59038 4.4589 8.23038V6.08036C4.4589 5.20036 5.1789 4.48038 6.0589 4.48038H8.2089C8.5689 4.48038 9.0789 4.27041 9.3389 4.01041L10.8589 2.49039C11.4789 1.87039 12.4989 1.87039 13.1189 2.49039L14.6389 4.01041C14.8989 4.27041 15.4089 4.48038 15.7689 4.48038H17.9189C18.7989 4.48038 19.5189 5.20036 19.5189 6.08036V8.23038C19.5189 8.59038 19.7289 9.10039 19.9889 9.36039L21.5089 10.8804C22.1289 11.5004 22.1289 12.5204 21.5089 13.1404L19.9889 14.6604C19.7289 14.9204 19.5189 15.4304 19.5189 15.7904V17.9403C19.5189 18.8203 18.7989 19.5404 17.9189 19.5404H15.7689C15.4089 19.5404 14.8989 19.7504 14.6389 20.0104L13.1189 21.5304C12.4989 22.1504 11.4789 22.1504 10.8589 21.5304L9.3389 20.0104C9.0789 19.7504 8.5689 19.5404 8.2089 19.5404H6.0589C5.1789 19.5404 4.4589 18.8203 4.4589 17.9403V15.7904C4.4589 15.4204 4.2489 14.9104 3.9889 14.6604Z\" stroke=\"#ff0000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M9 15L15 9\" stroke=\"#ff0000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M14.4945 14.5H14.5035\" stroke=\"#ff0000\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M9.49451 9.5H9.50349\" stroke=\"#ff0000\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </g>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </svg><span class='text-danger'>{$bDiscount}%</span>";
                                } ?>
                        </h5>
                        <?php } ?>


                        <?php if (!$physicalUnavailable) { ?>
                        <h5 class='mt-3 none align-items-center mb-0' id='hardcoverPrice'>
                            <span class='fw-normal'>Price:</span>&nbsp;&nbsp;<span
                                class='<?php if ($bDiscount) {
                                    echo 'text-decoration-line-through';
                                } ?>'>$<?php echo $bPhysicalPrice; ?></span><?php if ($bDiscount) {
                                    $discountedPhysicalPrice = round(($bPhysicalPrice * (100.0 - $bDiscount)) / 100, 2);
                                    echo "&nbsp;&nbsp;<span>\${$discountedPhysicalPrice}</span>&nbsp;&nbsp;<svg width=\"32px\" height=\"32px\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" stroke=\"#ff0000\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <g id=\"SVGRepo_bgCarrier\" stroke-width=\"0\"></g>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <g id=\"SVGRepo_tracerCarrier\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></g>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <g id=\"SVGRepo_iconCarrier\">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M3.9889 14.6604L2.46891 13.1404C1.84891 12.5204 1.84891 11.5004 2.46891 10.8804L3.9889 9.36039C4.2489 9.10039 4.4589 8.59038 4.4589 8.23038V6.08036C4.4589 5.20036 5.1789 4.48038 6.0589 4.48038H8.2089C8.5689 4.48038 9.0789 4.27041 9.3389 4.01041L10.8589 2.49039C11.4789 1.87039 12.4989 1.87039 13.1189 2.49039L14.6389 4.01041C14.8989 4.27041 15.4089 4.48038 15.7689 4.48038H17.9189C18.7989 4.48038 19.5189 5.20036 19.5189 6.08036V8.23038C19.5189 8.59038 19.7289 9.10039 19.9889 9.36039L21.5089 10.8804C22.1289 11.5004 22.1289 12.5204 21.5089 13.1404L19.9889 14.6604C19.7289 14.9204 19.5189 15.4304 19.5189 15.7904V17.9403C19.5189 18.8203 18.7989 19.5404 17.9189 19.5404H15.7689C15.4089 19.5404 14.8989 19.7504 14.6389 20.0104L13.1189 21.5304C12.4989 22.1504 11.4789 22.1504 10.8589 21.5304L9.3389 20.0104C9.0789 19.7504 8.5689 19.5404 8.2089 19.5404H6.0589C5.1789 19.5404 4.4589 18.8203 4.4589 17.9403V15.7904C4.4589 15.4204 4.2489 14.9104 3.9889 14.6604Z\" stroke=\"#ff0000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M9 15L15 9\" stroke=\"#ff0000\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M14.4945 14.5H14.5035\" stroke=\"#ff0000\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path d=\"M9.49451 9.5H9.50349\" stroke=\"#ff0000\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </g>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </svg><span class='text-danger'>{$bDiscount}%</span>";
                                } ?>
                        </h5>
                        <?php } ?>


                        <?php if (!$physicalUnavailable) { ?>
                        <div class='mt-3 align-items-center none' id='amountDisplayer'>
                            <div class="btn-group" role="group">
                                <input aria-label='Decrease amount' onclick='adjustAmount(false)' type="button"
                                    class="btn-check" id="decrease_book_ammount" autocomplete="off">
                                <label class="btn btn-sm btn-secondary" for="decrease_book_ammount">-</label>

                                <input onchange='checkAmmount()' type="number"
                                    class="fw-bold ammount_input ps-2 border border-2 border-secondary" id="book_ammount"
                                    autocomplete="off" value="<?php if ($bInStock) {
                                        echo 1;
                                    } else {
                                        echo 0;
                                    } ?>" <?php if ($bInStock) {
                                        echo 'min="1"';
                                    } ?>
                                    max="<?php echo $bInStock; ?>">

                                <input aria-label='Increase amount' onclick='adjustAmount(true)' type="button"
                                    class="btn-check" id="increase_book_ammount" autocomplete="off">
                                <label class="btn btn-sm btn-secondary" for="increase_book_ammount">+</label>
                            </div>
                            <p class='mb-0 ms-3'>In stock: <strong id='in_stock'><?php echo $bInStock; ?></strong></p>
                        </div>
                        <?php } ?>

                        <?php
                        if (!check_session()) {
                            echo "<a href='/authentication/' class='btn btn-primary mt-3'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class='bi bi-cart4'></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Add to cart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>";
                        } elseif (check_session() && $_SESSION['type'] === 'customer') {
                            echo "<button type='submit' class='btn btn-primary mt-3' disabled id='addToCartBtn'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class='bi bi-cart4'></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Add to cart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>";
                        }
                        ?>
                    </form> --}}
                </div>
            </div>
            <div class='mt-4'>
                <h5>Description: </h5>
                <p class="text-justify">{{ $book->description }}</p>
            </div>
        </div>
        @livewire('customer.book.detail.rating')
    </div>
@endsection

@section('postloads')
    @livewireScripts
@endsection
